sonar.projectKey=Snookerrio_eco-service
sonar.projectName=Eco-Service
sonar.organization=snookerrio
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=reports/junit/junit.xml
sonar.exclusions=node_modules/**,coverage/**,docs/**
